import { IAttachResult, IBase } from './base.interface.js';
export declare namespace bsType {
    const grid: readonly [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "sm-0", "sm-1", "sm-2", "sm-3", "sm-4", "sm-5", "sm-6", "sm-7", "sm-8", "sm-9", "sm-10", "sm-11", "sm-12", "md-0", "md-1", "md-2", "md-3", "md-4", "md-5", "md-6", "md-7", "md-8", "md-9", "md-10", "md-11", "md-12", "lg-0", "lg-1", "lg-2", "lg-3", "lg-4", "lg-5", "lg-6", "lg-7", "lg-8", "lg-9", "lg-10", "lg-11", "lg-12", "xl-0", "xl-1", "xl-2", "xl-3", "xl-4", "xl-5", "xl-6", "xl-7", "xl-8", "xl-9", "xl-10", "xl-11", "xl-12", "xxl-0", "xxl-1", "xxl-2", "xxl-3", "xxl-4", "xxl-5", "xxl-6", "xxl-7", "xxl-8", "xxl-9", "xxl-10", "xxl-11", "xxl-12"];
    const flex: readonly ["row", "row-reverse", "column", "column-reverse", "wrap", "wrap-reverse", "nowrap", "fill", "shrink-0", "shrink-1", "grow-0", "grow-1", "sm-row", "sm-row-reverse", "sm-column", "sm-column-reverse", "sm-wrap", "sm-wrap-reverse", "sm-nowrap", "sm-fill", "sm-shrink-0", "sm-shrink-1", "sm-grow-0", "sm-grow-1", "md-row", "md-row-reverse", "md-column", "md-column-reverse", "md-wrap", "md-wrap-reverse", "md-nowrap", "md-fill", "md-shrink-0", "md-shrink-1", "md-grow-0", "md-grow-1", "lg-row", "lg-row-reverse", "lg-column", "lg-column-reverse", "lg-wrap", "lg-wrap-reverse", "lg-nowrap", "lg-fill", "lg-shrink-0", "lg-shrink-1", "lg-grow-0", "lg-grow-1", "xl-row", "xl-row-reverse", "xl-column", "xl-column-reverse", "xl-wrap", "xl-wrap-reverse", "xl-nowrap", "xl-fill", "xl-shrink-0", "xl-shrink-1", "xl-grow-0", "xl-grow-1", "xxl-row", "xxl-row-reverse", "xxl-column", "xxl-column-reverse", "xxl-wrap", "xxl-wrap-reverse", "xxl-nowrap", "xxl-fill", "xxl-shrink-0", "xxl-shrink-1", "xxl-grow-0", "xxl-grow-1"];
    const float: readonly ["start", "end", "none", "sm-start", "sm-end", "sm-none", "md-start", "md-end", "md-none", "lg-start", "lg-end", "lg-none", "xl-start", "xl-end", "xl-none", "xxl-start", "xxl-end", "xxl-none"];
    const order: readonly ["first", 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "last", "sm-first", "sm-0", "sm-1", "sm-2", "sm-3", "sm-4", "sm-5", "sm-6", "sm-7", "sm-8", "sm-9", "sm-10", "sm-11", "sm-12", "sm-last", "md-first", "md-0", "md-1", "md-2", "md-3", "md-4", "md-5", "md-6", "md-7", "md-8", "md-9", "md-10", "md-11", "md-12", "md-last", "lg-first", "lg-0", "lg-1", "lg-2", "lg-3", "lg-4", "lg-5", "lg-6", "lg-7", "lg-8", "lg-9", "lg-10", "lg-11", "lg-12", "lg-last", "xl-first", "xl-0", "xl-1", "xl-2", "xl-3", "xl-4", "xl-5", "xl-6", "xl-7", "xl-8", "xl-9", "xl-10", "xl-11", "xl-12", "xl-last", "xxl-first", "xxl-0", "xxl-1", "xxl-2", "xxl-3", "xxl-4", "xxl-5", "xxl-6", "xxl-7", "xxl-8", "xxl-9", "xxl-10", "xxl-11", "xxl-12", "xxl-last"];
    const offset: readonly [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "sm-0", "sm-1", "sm-2", "sm-3", "sm-4", "sm-5", "sm-6", "sm-7", "sm-8", "sm-9", "sm-10", "sm-11", "sm-12", "md-0", "md-1", "md-2", "md-3", "md-4", "md-5", "md-6", "md-7", "md-8", "md-9", "md-10", "md-11", "md-12", "lg-0", "lg-1", "lg-2", "lg-3", "lg-4", "lg-5", "lg-6", "lg-7", "lg-8", "lg-9", "lg-10", "lg-11", "lg-12", "xl-0", "xl-1", "xl-2", "xl-3", "xl-4", "xl-5", "xl-6", "xl-7", "xl-8", "xl-9", "xl-10", "xl-11", "xl-12", "xxl-0", "xxl-1", "xxl-2", "xxl-3", "xxl-4", "xxl-5", "xxl-6", "xxl-7", "xxl-8", "xxl-9", "xxl-10", "xxl-11", "xxl-12"];
    const align: readonly ["start", "end", "center", "baseline", "stretch", "sm-start", "sm-end", "sm-center", "sm-baseline", "sm-stretch", "md-start", "md-end", "md-center", "md-baseline", "md-stretch", "lg-start", "lg-end", "lg-center", "lg-baseline", "lg-stretch", "xl-start", "xl-end", "xl-center", "xl-baseline", "xl-stretch", "xxl-start", "xxl-end", "xxl-center", "xxl-baseline", "xxl-stretch"];
    const alignContent: readonly ["start", "end", "center", "between", "around", "stretch", "sm-start", "sm-end", "sm-center", "sm-between", "sm-around", "sm-stretch", "md-start", "md-end", "md-center", "md-between", "md-around", "md-stretch", "lg-start", "lg-end", "lg-center", "lg-between", "lg-around", "lg-stretch", "xl-start", "xl-end", "xl-center", "xl-between", "xl-around", "xl-stretch", "xxl-start", "xxl-end", "xxl-center", "xxl-between", "xxl-around", "xxl-stretch"];
    const justifyContent: readonly ["start", "end", "center", "between", "around", "evenly", "sm-start", "sm-end", "sm-center", "sm-between", "sm-around", "sm-evenly", "md-start", "md-end", "md-center", "md-between", "md-around", "md-evenly", "lg-start", "lg-end", "lg-center", "lg-between", "lg-around", "lg-evenly", "xl-start", "xl-end", "xl-center", "xl-between", "xl-around", "xl-evenly", "xxl-start", "xxl-end", "xxl-center", "xxl-between", "xxl-around", "xxl-evenly"];
    const alignItem: readonly ["start", "end", "center", "baseline", "stretch", "sm-start", "sm-end", "sm-center", "sm-baseline", "sm-stretch", "md-start", "md-end", "md-center", "md-baseline", "md-stretch", "lg-start", "lg-end", "lg-center", "lg-baseline", "lg-stretch", "xl-start", "xl-end", "xl-center", "xl-baseline", "xl-stretch", "xxl-start", "xxl-end", "xxl-center", "xxl-baseline", "xxl-stretch"];
    const alignSelf: readonly ["start", "end", "center", "baseline", "stretch", "sm-start", "sm-end", "sm-center", "sm-baseline", "sm-stretch", "md-start", "md-end", "md-center", "md-baseline", "md-stretch", "lg-start", "lg-end", "lg-center", "lg-baseline", "lg-stretch", "xl-start", "xl-end", "xl-center", "xl-baseline", "xl-stretch", "xxl-start", "xxl-end", "xxl-center", "xxl-baseline", "xxl-stretch"];
    const spacer: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const display: readonly ["none", "inline", "inline-block", "block", "grid", "table", "table-cell", "table-row", "flex", "inline-flex", "sm-none", "sm-inline", "sm-inline-block", "sm-block", "sm-grid", "sm-table", "sm-table-cell", "sm-table-row", "sm-flex", "sm-inline-flex", "md-none", "md-inline", "md-inline-block", "md-block", "md-grid", "md-table", "md-table-cell", "md-table-row", "md-flex", "md-inline-flex", "lg-none", "lg-inline", "lg-inline-block", "lg-block", "lg-grid", "lg-table", "lg-table-cell", "lg-table-row", "lg-flex", "lg-inline-flex", "xl-none", "xl-inline", "xl-inline-block", "xl-block", "xl-grid", "xl-table", "xl-table-cell", "xl-table-row", "xl-flex", "xl-inline-flex", "xxl-none", "xxl-inline", "xxl-inline-block", "xxl-block", "xxl-grid", "xxl-table", "xxl-table-cell", "xxl-table-row", "xxl-flex", "xxl-inline-flex"];
    const rowCol: readonly ["auto", 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "sm-auto", "sm-0", "sm-1", "sm-2", "sm-3", "sm-4", "sm-5", "sm-6", "sm-7", "sm-8", "sm-9", "sm-10", "sm-11", "sm-12", "md-auto", "md-0", "md-1", "md-2", "md-3", "md-4", "md-5", "md-6", "md-7", "md-8", "md-9", "md-10", "md-11", "md-12", "lg-auto", "lg-0", "lg-1", "lg-2", "lg-3", "lg-4", "lg-5", "lg-6", "lg-7", "lg-8", "lg-9", "lg-10", "lg-11", "lg-12", "xl-auto", "xl-0", "xl-1", "xl-2", "xl-3", "xl-4", "xl-5", "xl-6", "xl-7", "xl-8", "xl-9", "xl-10", "xl-11", "xl-12", "xxl-auto", "xxl-0", "xxl-1", "xxl-2", "xxl-3", "xxl-4", "xxl-5", "xxl-6", "xxl-7", "xxl-8", "xxl-9", "xxl-10", "xxl-11", "xxl-12"];
    const color: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const positionView: readonly ["start", "sm-start", "md-start", "lg-start", "xl-start", "center", "sm-center", "md-center", "lg-center", "xl-center", "end", "sm-end", "md-end", "lg-end", "xl-end"];
    const visible: readonly [true, false];
    const textWrap: readonly [true, false];
    const fontItalic: readonly [true, false];
    const bgGradient: readonly [true];
    const wordBreak: readonly [true];
    const monospace: readonly [true];
    const placeholder: readonly [true];
    const row: readonly [true, false];
    const col: readonly [true, "auto", 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "sm-auto", "sm-0", "sm-1", "sm-2", "sm-3", "sm-4", "sm-5", "sm-6", "sm-7", "sm-8", "sm-9", "sm-10", "sm-11", "sm-12", "md-auto", "md-0", "md-1", "md-2", "md-3", "md-4", "md-5", "md-6", "md-7", "md-8", "md-9", "md-10", "md-11", "md-12", "lg-auto", "lg-0", "lg-1", "lg-2", "lg-3", "lg-4", "lg-5", "lg-6", "lg-7", "lg-8", "lg-9", "lg-10", "lg-11", "lg-12", "xl-auto", "xl-0", "xl-1", "xl-2", "xl-3", "xl-4", "xl-5", "xl-6", "xl-7", "xl-8", "xl-9", "xl-10", "xl-11", "xl-12", "xxl-auto", "xxl-0", "xxl-1", "xxl-2", "xxl-3", "xxl-4", "xxl-5", "xxl-6", "xxl-7", "xxl-8", "xxl-9", "xxl-10", "xxl-11", "xxl-12"];
    const userSelect: readonly ["all", "auto", "none"];
    const pointerEvent: readonly ["auto", "none"];
    const position: readonly ["static", "relative"];
    const overflow: readonly ["auto", "hidden", "scroll"];
    const textAlign: readonly ["start", "sm-start", "md-start", "lg-start", "xl-start", "center", "sm-center", "md-center", "lg-center", "xl-center", "end", "sm-end", "md-end", "lg-end", "xl-end"];
    const verticalAlign: readonly ["baseline", "top", "middle", "bottom", "text-top", "text-bottom"];
    const opacity: readonly [0, 25, 50, 75, 100];
    const bgOpacity: readonly [10, 25, 50, 75, 100];
    const textOpacity: readonly [25, 50, 75, 100];
    const btnColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const btnOutlineColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const alertColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const textBgColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const textColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const linkColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const bgColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const textTransform: readonly ["lowercase", "uppercase", "capitalize"];
    const textDecoration: readonly ["underline", "line-through", "none"];
    const lineHeight: readonly [1, "sm", "base", "lg"];
    const fontSize: readonly [1, 2, 3, 4, 5, 6];
    const fontWeight: readonly ["bold", "bolder", "normal", "light", "lighter"];
    const top: readonly [0, 50, 100];
    const bottom: readonly [0, 50, 100];
    const start: readonly [0, 50, 100];
    const end: readonly [0, 50, 100];
    const tMiddle: readonly [true, "x", "y"];
    const height: readonly ["auto", 25, 50, 75, 100];
    const width: readonly ["auto", 25, 50, 75, 100];
    const maxHeight: readonly [100];
    const maxWidth: readonly [100];
    const minViewHeight: readonly [100];
    const minViewWidth: readonly [100];
    const viewHeight: readonly [100];
    const viewWidth: readonly [100];
    const placeholderAnimation: readonly ["glow", "wave"];
    const placeholderWeight: readonly ["lg", "sm", "xs"];
    const shadow: readonly [true, false, "none", "sm", "lg", "inset"];
    const borderNone: readonly [true, "top", "end", "bottom", "start"];
    const border: readonly [true, false, "top", "end", "bottom", "start"];
    const borderColor: readonly ["primary", "secondary", "success", "danger", "warning", "info", "light", "dark"];
    const borderOpacity: readonly [10, 25, 50, 75];
    const borderWidth: number[];
    const roundedNone: readonly [true, false, "top", "end", "bottom", "start"];
    const rounded: readonly [true, false, "top", "end", "bottom", "start", "circle", "pill"];
    const roundedSize: number[];
    const padding: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const paddingX: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const paddingY: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const paddingTop: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const paddingBottom: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const paddingStart: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const paddingEnd: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const margin: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const marginX: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const marginY: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const marginTop: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const marginBottom: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const marginStart: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const marginEnd: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const gap: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const gutter: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const gutterX: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const gutterY: readonly [0, 1, 2, 3, 4, 5, "auto", "sm-0", "md-0", "lg-0", "xl-0", "xxl-0", "sm-1", "md-1", "lg-1", "xl-1", "xxl-1", "sm-2", "md-2", "lg-2", "xl-2", "xxl-2", "sm-3", "md-3", "lg-3", "xl-3", "xxl-3", "sm-4", "md-4", "lg-4", "xl-4", "xxl-4", "sm-5", "md-5", "lg-5", "xl-5", "xxl-5", "sm-auto", "md-auto", "lg-auto", "xl-auto", "xxl-auto"];
    const print: readonly ["none", "inline", "inline-block", "block", "grid", "table", "table-cell", "table-row", "flex", "inline-flex", "sm-none", "sm-inline", "sm-inline-block", "sm-block", "sm-grid", "sm-table", "sm-table-cell", "sm-table-row", "sm-flex", "sm-inline-flex", "md-none", "md-inline", "md-inline-block", "md-block", "md-grid", "md-table", "md-table-cell", "md-table-row", "md-flex", "md-inline-flex", "lg-none", "lg-inline", "lg-inline-block", "lg-block", "lg-grid", "lg-table", "lg-table-cell", "lg-table-row", "lg-flex", "lg-inline-flex", "xl-none", "xl-inline", "xl-inline-block", "xl-block", "xl-grid", "xl-table", "xl-table-cell", "xl-table-row", "xl-flex", "xl-inline-flex", "xxl-none", "xxl-inline", "xxl-inline-block", "xxl-block", "xxl-grid", "xxl-table", "xxl-table-cell", "xxl-table-row", "xxl-flex", "xxl-inline-flex"];
    const container: (string | boolean)[];
}
export declare namespace bs {
    type spacer = typeof bsType.spacer;
    type display = typeof bsType.display;
    type flex = typeof bsType.flex;
    type justifyContent = typeof bsType.justifyContent;
    type align = typeof bsType.align;
    type alignContent = typeof bsType.alignContent;
    type alignItem = typeof bsType.align;
    type alignSelf = typeof bsType.align;
    type order = typeof bsType.order;
    type grid = typeof bsType.grid;
    type offset = typeof bsType.grid;
    type rowCol = typeof bsType.rowCol;
    type float = typeof bsType.float;
    type color = typeof bsType.color;
    type positionView = typeof bsType.positionView;
    type visible = typeof bsType.visible;
    type textWrap = typeof bsType.textWrap;
    type fontItalic = typeof bsType.fontItalic;
    type bgGradient = typeof bsType.bgGradient;
    type wordBreak = typeof bsType.wordBreak;
    type monospace = typeof bsType.monospace;
    type placeholder = typeof bsType.placeholder;
    type row = typeof bsType.row;
    type col = typeof bsType.col;
    type userSelect = typeof bsType.userSelect;
    type pointerEvent = typeof bsType.pointerEvent;
    type position = typeof bsType.position;
    type overflow = typeof bsType.overflow;
    type textAlign = typeof bsType.textAlign;
    type verticalAlign = typeof bsType.verticalAlign;
    type opacity = typeof bsType.opacity;
    type bgOpacity = typeof bsType.bgOpacity;
    type textOpacity = typeof bsType.textOpacity;
    type textBgColor = typeof bsType.textBgColor;
    type textColor = typeof bsType.textColor;
    type bgColor = typeof bsType.bgColor;
    type textTransform = typeof bsType.textTransform;
    type textDecoration = typeof bsType.textDecoration;
    type lineHeight = typeof bsType.lineHeight;
    type fontSize = typeof bsType.fontSize;
    type fontWeight = typeof bsType.fontWeight;
    type top = typeof bsType.top;
    type bottom = typeof bsType.bottom;
    type start = typeof bsType.start;
    type end = typeof bsType.end;
    type tMiddle = typeof bsType.tMiddle;
    type height = typeof bsType.height;
    type width = typeof bsType.width;
    type maxHeight = typeof bsType.maxHeight;
    type maxWidth = typeof bsType.maxWidth;
    type minViewHeight = typeof bsType.minViewHeight;
    type minViewWidth = typeof bsType.minViewWidth;
    type viewHeight = typeof bsType.viewHeight;
    type viewWidth = typeof bsType.viewWidth;
    type placeholderAnimation = typeof bsType.placeholderAnimation;
    type placeholderWeight = typeof bsType.placeholderWeight;
    type shadow = typeof bsType.shadow;
    type borderNone = typeof bsType.borderNone;
    type border = typeof bsType.border;
    type borderColor = typeof bsType.borderColor;
    type borderOpacity = typeof bsType.borderOpacity;
    type borderWidth = typeof bsType.borderWidth;
    type roundedNone = typeof bsType.roundedNone;
    type rounded = typeof bsType.rounded;
    type roundedSize = typeof bsType.roundedSize;
    type padding = typeof bsType.padding;
    type paddingX = typeof bsType.paddingX;
    type paddingY = typeof bsType.paddingY;
    type paddingTop = typeof bsType.paddingTop;
    type paddingBottom = typeof bsType.paddingBottom;
    type paddingStart = typeof bsType.paddingStart;
    type paddingEnd = typeof bsType.paddingEnd;
    type margin = typeof bsType.margin;
    type marginX = typeof bsType.marginX;
    type marginY = typeof bsType.marginY;
    type marginTop = typeof bsType.marginTop;
    type marginBottom = typeof bsType.marginBottom;
    type marginStart = typeof bsType.marginStart;
    type marginEnd = typeof bsType.marginEnd;
    type gap = typeof bsType.gap;
    type gutter = typeof bsType.gutter;
    type gutterX = typeof bsType.gutterX;
    type gutterY = typeof bsType.gutterY;
    type print = typeof bsType.print;
    type container = typeof bsType.container;
}
export declare const attachBootstrap: (key: string, elem: HTMLElement, opt: IBase) => IAttachResult;
